create table public.medical_directory_raw (
  medical_directory_id text not null,
  speciality_cod integer null,
  speciality text null,
  online_appointment integer null,
  electronic_prescription integer null,
  virtual_consultation integer null,
  attention_type_id integer null,
  biller text null,
  company_cod integer null,
  networks text[] null,
  professional_id integer null,
  professional_nif text null,
  professional_name text null,
  professional_last_name_1 text null,
  professional_last_name_2 text null,
  professional_nick_name text null,
  professional_membership_number text null,
  professional_province integer null,
  professional_expert_in text null,
  professional_curriculum_vitae text null,
  professional_average_rating text null,
  sp_id integer null,
  sp_preferential text null,
  sp_name text null,
  sp_last_name_1 text null,
  sp_last_name_2 text null,
  sp_customer_telephone_1 bigint null,
  sp_customer_telephone_2 bigint null,
  sp_email_1 text null,
  sp_email_2 text null,
  sp_schedule_1 text null,
  sp_schedule_2 text null,
  sp_web_site text null,
  sp_point_contact_id text null,
  sp_is_health_space integer null,
  sp_average_rating text null,
  sp_is_colaborator integer null,
  nature_cod text null,
  nature text null,
  road_type text null,
  road text null,
  address_id integer null,
  address_cod integer null,
  address text null,
  town text null,
  province text null,
  postal_code integer null,
  latitude double precision null,
  longitude double precision null,
  location_gis geography null,
  merge_order text null,
  weight_sorting integer null,
  combined_name text null,
  prescription_without_authorization integer null,
  is_center integer null,
  last_modified timestamp without time zone null,
  specialists_01 text null,
  specialists_02 text null,
  specialists_03 text null,
  specialists_04 text null,
  canonical integer null,
  ofuscate_document_id text null,
  constraint medical_directory_raw_pkey primary key (medical_directory_id)
) TABLESPACE pg_default;